apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: pingpong 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pingpong 
    spec:
      containers:
        - name: pingpong 
          image: mtrrepository.azurecr.io/pingpong
          ports:
          - containerPort: 8080